spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:shoppingmall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true


  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
